In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn as skl
from tensorflow.keras import layers, models

2024-03-13 15:09:54.334390: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-13 15:09:54.334419: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-13 15:09:54.335250: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-13 15:09:54.340081: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-13 15:09:54.931265: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

In [3]:
# file = 'Dataset/CSV files/kstrdplfeaturesreportoriginal-inintegralvalues.csv'

# df = pd.read_csv(file)
# df = df[df.Label_Desc == 'Benign type']
# shape = df.shape
# print(f"Shape = {shape}")

# df = df.drop(['filename','Label_Desc'], axis=1)
# df = df.fillna(0)
# df = df.astype(int)
# df.info()

In [4]:
# df.to_csv('real_benign.csv', index=False)

In [5]:
file = 'real_benign.csv'

real_df = pd.read_csv(file)
real_df

,fl_dur,tot_fw_pk,tot_bw_pk,tot_l_fw_pkt,fw_pkt_l_max,fw_pkt_l_min,fw_pkt_l_avg,fw_pkt_l_std,bw_pkt_l_max,bw_pkt_l_min,...,fw_iat_min,bw_iat_tot,bw_iat_avg,bw_iat_std,bw_iat_max,bw_iat_min,fw_pkt_s,bw_pkt_s,pkt_size_avg,Label_code
0,3,4,2,256,64,64,64,0,72,72,...,0,0,0,0,0,0,1,36,33,0
1,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,13,13,34,0
2,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,16,16,34,0
3,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,21,21,34,0
4,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,42,42,34,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88338,2,3,3,192,64,64,64,0,72,72,...,0,2,1,1,2,0,2,2,34,0
88339,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,19,19,34,0
88340,1,3,3,192,64,64,64,0,72,72,...,0,1,0,0,1,0,4,4,34,0
88341,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,11,11,34,0
88342,1,3,3,192,64,64,64,0,72,72,...,0,1,0,0,1,0,4,4,34,0

In [6]:
real_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88343 entries, 0 to 88342
Data columns (total 30 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fl_dur         88343 non-null  int64
 1   tot_fw_pk      88343 non-null  int64
 2   tot_bw_pk      88343 non-null  int64
 3   tot_l_fw_pkt   88343 non-null  int64
 4   fw_pkt_l_max   88343 non-null  int64
 5   fw_pkt_l_min   88343 non-null  int64
 6   fw_pkt_l_avg   88343 non-null  int64
 7   fw_pkt_l_std   88343 non-null  int64
 8   bw_pkt_l_max   88343 non-null  int64
 9   bw_pkt_l_min   88343 non-null  int64
 10  bw_pkt_l_mean  88343 non-null  int64
 11  bw_pkt_l_std   88343 non-null  int64
 12  fw_fl_byt_s    88343 non-null  int64
 13  bw_fl_byt_s    88343 non-null  int64
 14  fw_fl_pkt_s    88343 non-null  int64
 15  bw_fl_pkt_s    88343 non-null  int64
 16  fw_iat_tot     88343 non-null  int64
 17  fw_iat_avg     88343 non-null  int64
 18  fw_iat_std     88343 non-null  int64
 19  fw_iat_max     88343 non-null  int64
 20  fw_iat_min     88343 non-null  int64
 21  bw_iat_tot     88343 non-null  int64
 22  bw_iat_avg     88343 non-null  int64
 23  bw_iat_std     88343 non-null  int64
 24  bw_iat_max     88343 non-null  int64
 25  bw_iat_min     88343 non-null  int64
 26  fw_pkt_s       88343 non-null  int64
 27  bw_pkt_s       88343 non-null  int64
 28  pkt_size_avg   88343 non-null  int64
 29  Label_code     88343 non-null  int64
dtypes: int64(30)
memory usage: 20.2 MB

In [7]:
file_b = 'Augmented Dataset/aug_benign_8x1000.csv'
file_c = 'aug_benign.csv'

aug_df = pd.read_csv(file_c)
aug_df

,fl_dur,tot_fw_pk,tot_bw_pk,tot_l_fw_pkt,fw_pkt_l_max,fw_pkt_l_min,fw_pkt_l_avg,fw_pkt_l_std,bw_pkt_l_max,bw_pkt_l_min,...,fw_iat_min,bw_iat_tot,bw_iat_avg,bw_iat_std,bw_iat_max,bw_iat_min,fw_pkt_s,bw_pkt_s,pkt_size_avg,Label_code
0,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,10,10,34,1
1,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,12,12,34,1
2,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,10,10,34,1
3,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,13,13,34,1
4,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,10,10,34,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88338,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,13,13,34,1
88339,1,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,3,3,34,1
88340,1,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,3,3,34,1
88341,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,7,7,34,1
88342,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,4,4,34,1

In [8]:
aug_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88343 entries, 0 to 88342
Data columns (total 30 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fl_dur         88343 non-null  int64
 1   tot_fw_pk      88343 non-null  int64
 2   tot_bw_pk      88343 non-null  int64
 3   tot_l_fw_pkt   88343 non-null  int64
 4   fw_pkt_l_max   88343 non-null  int64
 5   fw_pkt_l_min   88343 non-null  int64
 6   fw_pkt_l_avg   88343 non-null  int64
 7   fw_pkt_l_std   88343 non-null  int64
 8   bw_pkt_l_max   88343 non-null  int64
 9   bw_pkt_l_min   88343 non-null  int64
 10  bw_pkt_l_mean  88343 non-null  int64
 11  bw_pkt_l_std   88343 non-null  int64
 12  fw_fl_byt_s    88343 non-null  int64
 13  bw_fl_byt_s    88343 non-null  int64
 14  fw_fl_pkt_s    88343 non-null  int64
 15  bw_fl_pkt_s    88343 non-null  int64
 16  fw_iat_tot     88343 non-null  int64
 17  fw_iat_avg     88343 non-null  int64
 18  fw_iat_std     88343 non-null  int64
 19  fw_iat_max     88343 non-null  int64
 20  fw_iat_min     88343 non-null  int64
 21  bw_iat_tot     88343 non-null  int64
 22  bw_iat_avg     88343 non-null  int64
 23  bw_iat_std     88343 non-null  int64
 24  bw_iat_max     88343 non-null  int64
 25  bw_iat_min     88343 non-null  int64
 26  fw_pkt_s       88343 non-null  int64
 27  bw_pkt_s       88343 non-null  int64
 28  pkt_size_avg   88343 non-null  int64
 29  Label_code     88343 non-null  int64
dtypes: int64(30)
memory usage: 20.2 MB

In [9]:
combined_df = pd.concat([real_df, aug_df], ignore_index=True) 
combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [10]:
X = combined_df.drop(columns=['Label_code'])
y = combined_df['Label_code']

In [11]:
X

,fl_dur,tot_fw_pk,tot_bw_pk,tot_l_fw_pkt,fw_pkt_l_max,fw_pkt_l_min,fw_pkt_l_avg,fw_pkt_l_std,bw_pkt_l_max,bw_pkt_l_min,...,fw_iat_max,fw_iat_min,bw_iat_tot,bw_iat_avg,bw_iat_std,bw_iat_max,bw_iat_min,fw_pkt_s,bw_pkt_s,pkt_size_avg
0,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,1,0,1,1,34
1,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,5,5,34
2,2,3,3,192,64,64,64,0,72,72,...,2,0,2,1,2,2,0,1,1,34
3,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,94,94,34
4,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,16,16,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176681,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,14,14,34
176682,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,7,7,34
176683,1,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,2,2,34
176684,1,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,3,3,34
176685,0,3,3,192,64,64,64,0,72,72,...,0,0,0,0,0,0,0,17,17,34

In [12]:
y

0         1
1         1
2         0
3         0
4         1
         ..
176681    1
176682    1
176683    1
176684    1
176685    1
Name: Label_code, Length: 176686, dtype: int64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

Decision Tree

In [14]:
dt = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
dt = dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.6575025297134135

NB

In [15]:
nb = GaussianNB()
nb = nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.5903579330097587

MLP

In [16]:
mlp = MLPClassifier(hidden_layer_sizes=(9,9,9), activation='relu', solver='adam', max_iter=1000)
mlp = mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0

SVM

In [ ]:
svm =svm.SVC(gamma=0.001,C =0.1)
svm = svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy